# Generated by Django 4.1.5 on 2023-04-16 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cof",
            fields=[
                ("cof_id", models.UUIDField(primary_key=True, serialize=False)),
                ("date_roasted", models.DateField(blank=True, null=True)),
                ("date_best_by", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "cof",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CofPull",
            fields=[
                ("cofpull_id", models.UUIDField(primary_key=True, serialize=False)),
                ("grams_in", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("grams_out", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("cof_id", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="mysite.cof")),
            ],
            options={
                "db_table": "cof_pull",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CofComment",
            fields=[
                ("comment_name", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField()),
                ("cofcomment_id", models.UUIDField(primary_key=True, serialize=False)),
                ("comment_posted", models.DateTimeField()),
                ("cof_id", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="mysite.cof")),
                (
                    "cofpull_id",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="mysite.cofpull"),
                ),
            ],
            options={
                "db_table": "cof_comment",
                "managed": True,
            },
        ),
    ]
